

spring:
  datasource:
    url: jdbc:h2:mem:sbipdb
    driver-class-name: org.h2.Driver
    username: sa
    password: jason1653
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true