
spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  datasource:
    url: jdbc:h2:mem:testdb1
    driver-class-name: org.h2.Driver
    username: sa
    password: jason1653
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
