info:
  app:
    name: Spring Boot Actuator Info Application
    description: Spring Boot Actuator Info Application
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

    build:
      artifact: "@project.artifactId@"
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
      properties:
        java:
          version: "@java.version@"