version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: jason-mongodb
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: jason
      MONGO_INITDB_ROOT_PASSWORD: jason1653
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./data/mongodb:/data/db